version: "3.9"
services:
  auth-server:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 10s
      retries: 60
      start_period: 60ss
